// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSs4dPvARDS6VWCRntBPqTxVMmLDQSj-w',
    appId: '1:769266265384:web:598c00e2adacb43337b41d',
    messagingSenderId: '769266265384',
    projectId: 'sahilt-629bd',
    authDomain: 'sahilt-629bd.firebaseapp.com',
    storageBucket: 'sahilt-629bd.appspot.com',
    measurementId: 'G-YSLB3NVYMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ7b2_IWQ7XYSMwG1utE_H_GEPCxQ6MLs',
    appId: '1:769266265384:android:de1466c56021694237b41d',
    messagingSenderId: '769266265384',
    projectId: 'sahilt-629bd',
    storageBucket: 'sahilt-629bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAynur8J33j_MnqdkVoidPqUsSBhmDI1xk',
    appId: '1:769266265384:ios:c47ceabef2ef772c37b41d',
    messagingSenderId: '769266265384',
    projectId: 'sahilt-629bd',
    storageBucket: 'sahilt-629bd.appspot.com',
    iosBundleId: 'com.example.clg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAynur8J33j_MnqdkVoidPqUsSBhmDI1xk',
    appId: '1:769266265384:ios:c47ceabef2ef772c37b41d',
    messagingSenderId: '769266265384',
    projectId: 'sahilt-629bd',
    storageBucket: 'sahilt-629bd.appspot.com',
    iosBundleId: 'com.example.clg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSs4dPvARDS6VWCRntBPqTxVMmLDQSj-w',
    appId: '1:769266265384:web:baaac16d941bc6f637b41d',
    messagingSenderId: '769266265384',
    projectId: 'sahilt-629bd',
    authDomain: 'sahilt-629bd.firebaseapp.com',
    storageBucket: 'sahilt-629bd.appspot.com',
    measurementId: 'G-8TTBCKCCQ7',
  );
}
